### ISSUE TITLE
Add node level scenarios for Helper node

### ISSUE THREAD

**Issue by pravin-dsilva** [cloud-bulldozer/kraken#67]
The bastion or helper node is useful for deploying Openshift clusters and hosts a number of important services such as dhcpd, haproxy etc. Running node level tests on this node would be useful in checking its stability and the services running on it.

**Comment by pravin-dsilva** [comment]
Please review PR https://github.com/cloud-bulldozer/kraken/pull/68 and provide feedback. Thanks.

**Comment by mffiedler** [comment]
@pravin-dsilva Can you provide some more details of your topology and what the objective of this scenario is?   Part of my misunderstanding might be terminology.  To many of us, a bastion node (or "jump host") is a system which is on the same VPC/node host network as the control plane and workers in the cluster, but is not itself a node in the cluster.   The bastion (in this terminology) is used as an ssh or scp intermediary to be able to  access a node that is not otherwise publicly accessible and is not accessible via other debug tools such as "oc adm debug" in openshift.  

I see in this PR you are looking at services like haproxy, dhcpd and named on the bastion, so I assume the bastion is being used for some larger purpose than a simple ssh intermediary.   If you can provide more details (either here or a pointer to other documentation) it might help understand your definition of bastion and why it would be important to include it in the chaos scenarios.   Thanks.

**Comment by arcprabh** [comment]
@mffiedler 
The bastion node is not a part of the cluster but it hosts critical services required for the OCP cluster like the haproxy, DHCP service, DNS and a httpd service that is required to render the ignition config files to the OCP cluster at the time of cluster deployment. It is also referred to as helper node. Please check the community project regarding the helper node here https://github.com/RedHatOfficial/ocp4-helpernode

The reason why we proposed this as another node level chaos test is because when this node fails, then it could be a single point of failure for the OCP cluster because the cluster relies on the external services that is running on this host. If the load balancer or the DHCP service is unavailable, then the cluster  gets impacted.

**Comment by mffiedler** [comment]
Great,   I understand better now.   To avoid confusion, can you re-work the PR to consistently refer to the system under chaos testing as a helpernode or helper_node?   We can avoid overloading bastion.   Updating the README.md with that link would be helpful as well.   Thanks for the explanation and thanks for the PR!

**Comment by pravin-dsilva** [comment]
Thanks, I've now made changes to call bastion as helper_node in the PR as well as a few other minor changes to the code.

**Comment by mffiedler** [comment]
Resolved by #68
